# Generated by Django 4.1.2 on 2022-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
